#! /bin/sh

### BEGIN INIT INFO
# Provides:        senic_button
# Required-Start:  $syslog
# Required-Stop:   $syslog
# Default-Start:   2 3 4 5
# Default-Stop:
# Short-Description: Listens to button presses and reboots or facotry resets the device
### END INIT INFO

PATH=/sbin:/bin:/usr/bin:/usr/sbin

NAME=senic_button
DAEMON=/usr/sbin/senic_button.py
PIDFILE=/var/run/senic_button.pid

# Source function library.
. /etc/init.d/functions

startdaemon(){
	echo -n "Starting $NAME: "
	start-stop-daemon --start --quiet --oknodo --pidfile $PIDFILE --startas $DAEMON "$@"
	echo "done"
}
stopdaemon(){
	echo -n "Stopping $NAME: "
	start-stop-daemon --stop --quiet --oknodo -p $PIDFILE
	echo "done"
}

case "$1" in
  start)
	startdaemon
	;;
  stop)
  stopdaemon
	;;
  restart)
	stopdaemon
	startdaemon
	;;
  *)
	echo "Usage: ntpd { start | stop | restart }" >&2
	exit 1
	;;
esac

exit 0
