#!/bin/sh
### BEGIN INIT INFO
# Provides: update_motd
# Required-Start:
# Required-Stop:
# Default-Start:
# Default-Stop:
# Short-Description: Turn on the status LED once the system is booted
### END INIT INFO

echo -e "[Senic Hub] Turning on the status LED"

echo 198 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio198/direction
echo 1 > /sys/class/gpio/gpio198/active_low
echo 1 > /sys/class/gpio/gpio198/value
