#!/bin/bash

supervisorctl stop all
find /data/senic-hub/ -type f \! -name "production.ini" | xargs rm
nmcli --fields NAME con | awk '{if (NR!=1) {print $1}}' | while read -r line ; do nmcli con del $line; done
supervisorctl start all
