#!/usr/bin/python

import commands
from daemonize import Daemonize
import select
import time
import os

LOG_NAME = 'senic_hub_button_daemon'
DAEMON_PID = '/var/run/senic_hub_button_daemon.pid'

GPIO_PIN = '199'
GPIO_PATH = '/sys/class/gpio/'
PIN_PATH = GPIO_PATH + 'gpio' + GPIO_PIN + '/'

FACTORY_RESET = 3   # Factory reset after this many seconds
MAX_DURATION = 20   # Ignore button presses longer than this many seconds


def init_gpio():
    if not os.path.exists(PIN_PATH):
        write_file(GPIO_PATH + 'export', GPIO_PIN)
    write_file(PIN_PATH + 'direction', 'in')
    write_file(PIN_PATH + 'active_low', '1')
    write_file(PIN_PATH + 'edge', 'both')


def write_file(path, value):
    with open(path, 'w') as file_descriptor:
        file_descriptor.write(value)


def execute_and_log(command):
    daemon.logger.info("Executing: %s", command)
    output = commands.getstatusoutput(command)
    if output[1]:
        for line in output[1].split('\n'):
            daemon.logger.info("    " + line)


def on_press(press_duration):
    daemon.logger.info(
            "Reset button held for %0.2f seconds: FACTORY RESET" %
            press_duration)
    execute_and_log('/usr/bin/senic_hub_factory_reset')


def listen_for_button_presses():
    init_gpio()

    pin_value = open(PIN_PATH + 'value', 'r')
    pin_event = select.poll()
    pin_event.register(pin_value, select.POLLPRI)

    start = 0
    while True:
        pin_event.poll(None)  # Blocking until button state change

        pin_value.seek(0)
        state = pin_value.read()

        if state == "1\n":
            start = time.time()
        else:
            end = time.time()
            press_duration = end - start

            if press_duration >= FACTORY_RESET and \
               press_duration < MAX_DURATION:
                on_press(press_duration)


daemon = Daemonize(app=LOG_NAME,
                   pid=DAEMON_PID,
                   action=listen_for_button_presses)

daemon.start()
